<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attribute ID' => 'معرف الحقل',
    'Attribute name must contain latin word characters only.' => 'يجب أن يحتوي اسم الحقل على أحرف لاتينية فقط.',
    'Attribute {name} not found' => 'الحقل {name} غير موجودة',
    'Default Option ID' => 'معرف الخيار الافتراضي',
    'Default Value' => 'القيمة الافتراضية',
    'Default option Id' => 'معرف الخيار الافتراضي',
    'Description' => 'وصف',
    'Description En' => 'الوصف بالإنجليزية',
    'Dynamic model data were no attributes.' => ' بيانات الفورم الديناميكي لا تملك حقول.',
    'Dynamic model data were not save due to validation error.' => 'لم يتم حفظ بيانات الفورم الديناميكي بسبب خطأ في التحقق من الصحة.',
    'Entity ID' => 'معرف الكيان',
    'Entity Model' => 'نموذج الكيان',
    'Entity name' => 'اسم الكيان',
    'Handler Class' => 'فئة المعالج',
    'ID Category' => 'فئة المعرف',
    'ID Model' => 'نموذج الهوية',
    'Index Value' => 'قيمة المؤشر',
    'Label' => 'ملصق',
    'Label En' => 'التسمية En',
    'Locked' => 'مقفل',
    'Name' => 'اسم',
    'Option ID' => 'معرف الخيار',
    'Order' => 'ترتيب',
    'Plan App' => 'الخطة',
    'Required' => 'مطلوب',
    'Rules' => 'قواعد',
    'Sort order' => 'ترتيب',
    'Store Type' => 'نوع المتجر',
    'Template default attributes' => 'الحقول الإفتراضية للقالب',
    'Template field button' => 'زر حقل النموذج',
    'Template settings' => 'إعدادات النموذج',
    'Template view' => 'عرض النموذج',
    'Type' => 'نوع',
    'Type ID' => 'اكتب المعرف',
    'Type name must contain latin word characters only.' => 'يجب أن يحتوي اسم النوع على أحرف كلمة لاتينية فقط.',
    'Value' => 'قيمة',
    'Value En' => 'القيمة بالإنجليزية',
    'Visible' => 'معروض',
];
